-- Populate the canonical MEB teaching-field catalog used by PRO-LIG.
-- Idempotent: existing branches (for example Matematik) are preserved.
INSERT INTO "Branch" ("name", "category") VALUES
  ('Adalet', 'MEB'),
  ('Aile ve Tüketici Hizmetleri', 'MEB'),
  ('Almanca', 'MEB'),
  ('Arapça', 'MEB'),
  ('Ayakkabı ve Saraciye Teknolojisi', 'MEB'),
  ('Beden Eğitimi', 'MEB'),
  ('Bilişim Teknolojileri', 'MEB'),
  ('Biyoloji', 'MEB'),
  ('Biyomedikal Cihaz Teknolojileri', 'MEB'),
  ('Büro Yönetimi / Büro Yönetimi ve Yönetici Asistanlığı', 'MEB'),
  ('Coğrafya', 'MEB'),
  ('Çince', 'MEB'),
  ('Çocuk Gelişimi ve Eğitimi', 'MEB'),
  ('Denizcilik', 'MEB'),
  ('Din Kültürü ve Ahlâk Bilgisi', 'MEB'),
  ('El Sanatları Teknolojisi', 'MEB'),
  ('Elektrik-Elektronik Teknolojisi', 'MEB'),
  ('Endüstriyel Otomasyon Teknolojileri', 'MEB'),
  ('Felsefe', 'MEB'),
  ('Fen Bilimleri', 'MEB'),
  ('Fizik', 'MEB'),
  ('Fransızca', 'MEB'),
  ('Gazetecilik', 'MEB'),
  ('Gemi Yapımı', 'MEB'),
  ('Gıda Teknolojisi', 'MEB'),
  ('Giyim Üretim Teknolojisi / Moda Tasarım Teknolojileri', 'MEB'),
  ('Görsel Sanatlar', 'MEB'),
  ('Grafik ve Fotoğraf', 'MEB'),
  ('Güzellik ve Saç Bakım Hizmetleri / Güzellik Hizmetleri', 'MEB'),
  ('Halkla İlişkiler ve Organizasyon Hizmetleri / Halkla İlişkiler', 'MEB'),
  ('Harita-Tapu-Kadastro', 'MEB'),
  ('Hasta ve Yaşlı Hizmetleri', 'MEB'),
  ('Hayvan Sağlığı / Hayvan Yetiştiriciliği ve Sağlığı', 'MEB'),
  ('İlköğretim Matematik', 'MEB'),
  ('İmam-Hatip Lisesi Meslek Dersleri', 'MEB'),
  ('İngilizce', 'MEB'),
  ('İnşaat Teknolojisi', 'MEB'),
  ('İspanyolca', 'MEB'),
  ('İtalyanca', 'MEB'),
  ('İtfaiyecilik ve Yangın Güvenliği', 'MEB'),
  ('Japonca', 'MEB'),
  ('Kimya / Kimya Teknolojisi', 'MEB'),
  ('Konaklama ve Seyahat Hizmetleri', 'MEB'),
  ('Kuyumculuk Teknolojisi', 'MEB'),
  ('Laboratuvar Hizmetleri', 'MEB'),
  ('Makine Teknolojisi / Makine ve Tasarım Teknolojisi', 'MEB'),
  ('Matbaa / Matbaa Teknolojisi', 'MEB'),
  ('Matematik', 'MEB'),
  ('Metal Teknolojisi', 'MEB'),
  ('Metalürji Teknolojisi', 'MEB'),
  ('Mobilya ve İç Mekân Tasarımı', 'MEB'),
  ('Motorlu Araçlar Teknolojisi', 'MEB'),
  ('Muhasebe ve Finansman', 'MEB'),
  ('Müzik', 'MEB'),
  ('Müzik Aletleri Yapımı', 'MEB'),
  ('Okul Öncesi', 'MEB'),
  ('Özel Eğitim', 'MEB'),
  ('Pazarlama ve Perakende', 'MEB'),
  ('Plastik Teknolojisi', 'MEB'),
  ('Psikoloji', 'MEB'),
  ('Radyo-Televizyon', 'MEB'),
  ('Raylı Sistemler Teknolojisi', 'MEB'),
  ('Rehberlik', 'MEB'),
  ('Rusça', 'MEB'),
  ('Sağlık / Sağlık Hizmetleri', 'MEB'),
  ('Sağlık Bilgisi', 'MEB'),
  ('Sanat Tarihi', 'MEB'),
  ('Sanat ve Tasarım / Plastik Sanatlar', 'MEB'),
  ('Seramik ve Cam Teknolojisi', 'MEB'),
  ('Sınıf Öğretmenliği', 'MEB'),
  ('Sosyal Bilgiler', 'MEB'),
  ('Tarım Teknolojileri / Tarım', 'MEB'),
  ('Tarih', 'MEB'),
  ('Teknoloji ve Tasarım', 'MEB'),
  ('Tekstil Teknolojisi', 'MEB'),
  ('Tesisat Teknolojisi ve İklimlendirme', 'MEB'),
  ('Türkçe', 'MEB'),
  ('Türk Dili ve Edebiyatı', 'MEB'),
  ('Uçak Bakım', 'MEB'),
  ('Ulaştırma Hizmetleri', 'MEB'),
  ('Yenilenebilir Enerji Teknolojileri', 'MEB'),
  ('Yiyecek İçecek Hizmetleri', 'MEB'),
  ('Yaşayan Diller ve Lehçeler', 'MEB'),
  ('Maden Teknolojisi', 'MEB'),
  ('Farsça', 'MEB'),
  ('Korece', 'MEB'),
  ('Geleneksel Türk Sanatları', 'MEB'),
  ('Tiyatro', 'MEB'),
  ('Bilim Tarihi', 'MEB'),
  ('Bilgisayar ve Öğretim Teknolojileri', 'MEB')
ON CONFLICT ("name") DO NOTHING;
