export interface ProvinceSeed {
  id: number;
  code: string;
  name: string;
  region: string;
  districts: string[];
}

export const TURKEY_PROVINCES: ProvinceSeed[] = [
  { id: 1, code: '01', name: 'Adana', region: 'Akdeniz', districts: ['Seyhan', 'Yüreğir', 'Çukurova', 'Sarıçam'] },
  { id: 2, code: '02', name: 'Adıyaman', region: 'Güneydoğu Anadolu', districts: ['Merkez', 'Kahta', 'Besni'] },
  { id: 3, code: '03', name: 'Afyonkarahisar', region: 'Ege', districts: ['Merkez', 'Sandıklı', 'Dinar'] },
  { id: 4, code: '04', name: 'Ağrı', region: 'Doğu Anadolu', districts: ['Merkez', 'Doğubayazıt', 'Patnos'] },
  { id: 5, code: '05', name: 'Amasya', region: 'Karadeniz', districts: ['Merkez', 'Merzifon', 'Suluova'] },
  { id: 6, code: '06', name: 'Ankara', region: 'İç Anadolu', districts: ['Çankaya', 'Keçiören', 'Yenimahalle', 'Mamak', 'Etimesgut', 'Sincan'] },
  { id: 7, code: '07', name: 'Antalya', region: 'Akdeniz', districts: ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Alanya', 'Manavgat'] },
  { id: 8, code: '08', name: 'Artvin', region: 'Karadeniz', districts: ['Merkez', 'Hopa', 'Borçka'] },
  { id: 9, code: '09', name: 'Aydın', region: 'Ege', districts: ['Efeler', 'Nazilli', 'Söke', 'Kuşadası'] },
  { id: 10, code: '10', name: 'Balıkesir', region: 'Marmara', districts: ['Karesi', 'Altıeylül', 'Bandırma', 'Edremit'] },
  { id: 11, code: '11', name: 'Bilecik', region: 'Marmara', districts: ['Merkez', 'Bozüyük', 'Osmaneli'] },
  { id: 12, code: '12', name: 'Bingöl', region: 'Doğu Anadolu', districts: ['Merkez', 'Genç', 'Solhan'] },
  { id: 13, code: '13', name: 'Bitlis', region: 'Doğu Anadolu', districts: ['Merkez', 'Tatvan', 'Ahlat'] },
  { id: 14, code: '14', name: 'Bolu', region: 'Karadeniz', districts: ['Merkez', 'Gerede', 'Mengen'] },
  { id: 15, code: '15', name: 'Burdur', region: 'Akdeniz', districts: ['Merkez', 'Bucak', 'Gölhisar'] },
  { id: 16, code: '16', name: 'Bursa', region: 'Marmara', districts: ['Osmangazi', 'Nilüfer', 'Yıldırım', 'İnegöl', 'Gemlik'] },
  { id: 17, code: '17', name: 'Çanakkale', region: 'Marmara', districts: ['Merkez', 'Biga', 'Çan', 'Gelibolu'] },
  { id: 18, code: '18', name: 'Çankırı', region: 'İç Anadolu', districts: ['Merkez', 'Ilgaz', 'Çerkeş'] },
  { id: 19, code: '19', name: 'Çorum', region: 'Karadeniz', districts: ['Merkez', 'Sungurlu', 'Osmancık'] },
  { id: 20, code: '20', name: 'Denizli', region: 'Ege', districts: ['Pamukkale', 'Merkezefendi', 'Çivril', 'Acıpayam'] },
  { id: 21, code: '21', name: 'Diyarbakır', region: 'Güneydoğu Anadolu', districts: ['Bağlar', 'Kayapınar', 'Yenişehir', 'Sur', 'Ergani'] },
  { id: 22, code: '22', name: 'Edirne', region: 'Marmara', districts: ['Merkez', 'Keşan', 'Uzunköprü'] },
  { id: 23, code: '23', name: 'Elazığ', region: 'Doğu Anadolu', districts: ['Merkez', 'Kovancılar', 'Karakoçan'] },
  { id: 24, code: '24', name: 'Erzincan', region: 'Doğu Anadolu', districts: ['Merkez', 'Tercan', 'Üzümlü'] },
  { id: 25, code: '25', name: 'Erzurum', region: 'Doğu Anadolu', districts: ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan'] },
  { id: 26, code: '26', name: 'Eskişehir', region: 'İç Anadolu', districts: ['Odunpazarı', 'Tepebaşı', 'Sivrihisar'] },
  { id: 27, code: '27', name: 'Gaziantep', region: 'Güneydoğu Anadolu', districts: ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye'] },
  { id: 28, code: '28', name: 'Giresun', region: 'Karadeniz', districts: ['Merkez', 'Bulancak', 'Espiye'] },
  { id: 29, code: '29', name: 'Gümüşhane', region: 'Karadeniz', districts: ['Merkez', 'Kelkit', 'Şiran'] },
  { id: 30, code: '30', name: 'Hakkari', region: 'Doğu Anadolu', districts: ['Merkez', 'Yüksekova', 'Şemdinli'] },
  { id: 31, code: '31', name: 'Hatay', region: 'Akdeniz', districts: ['Antakya', 'İskenderun', 'Defne', 'Dörtyol'] },
  { id: 32, code: '32', name: 'Isparta', region: 'Akdeniz', districts: ['Merkez', 'Yalvaç', 'Eğirdir'] },
  { id: 33, code: '33', name: 'Mersin', region: 'Akdeniz', districts: ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Tarsus'] },
  { id: 34, code: '34', name: 'İstanbul', region: 'Marmara', districts: ['Kadıköy', 'Beşiktaş', 'Üsküdar', 'Fatih', 'Bakırköy', 'Maltepe', 'Ataşehir', 'Beylikdüzü', 'Şişli'] },
  { id: 35, code: '35', name: 'İzmir', region: 'Ege', districts: ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Çiğli', 'Gaziemir', 'Bayraklı'] },
  { id: 36, code: '36', name: 'Kars', region: 'Doğu Anadolu', districts: ['Merkez', 'Kağızman', 'Sarıkamış'] },
  { id: 37, code: '37', name: 'Kastamonu', region: 'Karadeniz', districts: ['Merkez', 'Tosya', 'Taşköprü'] },
  { id: 38, code: '38', name: 'Kayseri', region: 'İç Anadolu', districts: ['Melikgazi', 'Kocasinan', 'Talas', 'Develi'] },
  { id: 39, code: '39', name: 'Kırklareli', region: 'Marmara', districts: ['Merkez', 'Lüleburgaz', 'Babaeski'] },
  { id: 40, code: '40', name: 'Kırşehir', region: 'İç Anadolu', districts: ['Merkez', 'Kaman', 'Mucur'] },
  { id: 41, code: '41', name: 'Kocaeli', region: 'Marmara', districts: ['İzmit', 'Gebze', 'Darıca', 'Körfez', 'Gölcük'] },
  { id: 42, code: '42', name: 'Konya', region: 'İç Anadolu', districts: ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir'] },
  { id: 43, code: '43', name: 'Kütahya', region: 'Ege', districts: ['Merkez', 'Tavşanlı', 'Simav'] },
  { id: 44, code: '44', name: 'Malatya', region: 'Doğu Anadolu', districts: ['Battalgazi', 'Yeşilyurt', 'Doğanşehir'] },
  { id: 45, code: '45', name: 'Manisa', region: 'Ege', districts: ['Yunusemre', 'Şehzadeler', 'Akhisar', 'Turgutlu', 'Salihli'] },
  { id: 46, code: '46', name: 'Kahramanmaraş', region: 'Akdeniz', districts: ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin'] },
  { id: 47, code: '47', name: 'Mardin', region: 'Güneydoğu Anadolu', districts: ['Artuklu', 'Kızıltepe', 'Midyat', 'Nusaybin'] },
  { id: 48, code: '48', name: 'Muğla', region: 'Ege', districts: ['Menteşe', 'Bodrum', 'Fethiye', 'Milas', 'Marmaris'] },
  { id: 49, code: '49', name: 'Muş', region: 'Doğu Anadolu', districts: ['Merkez', 'Bulanık', 'Malazgirt'] },
  { id: 50, code: '50', name: 'Nevşehir', region: 'İç Anadolu', districts: ['Merkez', 'Ürgüp', 'Avanos'] },
  { id: 51, code: '51', name: 'Niğde', region: 'İç Anadolu', districts: ['Merkez', 'Bor', 'Çamardı'] },
  { id: 52, code: '52', name: 'Ordu', region: 'Karadeniz', districts: ['Altınordu', 'Ünye', 'Fatsa'] },
  { id: 53, code: '53', name: 'Rize', region: 'Karadeniz', districts: ['Merkez', 'Çayeli', 'Ardeşen'] },
  { id: 54, code: '54', name: 'Sakarya', region: 'Marmara', districts: ['Adapazarı', 'Serdivan', 'Akyazı', 'Erenler'] },
  { id: 55, code: '55', name: 'Samsun', region: 'Karadeniz', districts: ['İlkadım', 'Atakum', 'Canik', 'Bafra', 'Çarşamba'] },
  { id: 56, code: '56', name: 'Siirt', region: 'Güneydoğu Anadolu', districts: ['Merkez', 'Kurtalan', 'Pervari'] },
  { id: 57, code: '57', name: 'Sinop', region: 'Karadeniz', districts: ['Merkez', 'Boyabat', 'Gerze'] },
  { id: 58, code: '58', name: 'Sivas', region: 'İç Anadolu', districts: ['Merkez', 'Şarkışla', 'Yıldızeli', 'Suşehri'] },
  { id: 59, code: '59', name: 'Tekirdağ', region: 'Marmara', districts: ['Süleymanpaşa', 'Çorlu', 'Çerkezköy'] },
  { id: 60, code: '60', name: 'Tokat', region: 'Karadeniz', districts: ['Merkez', 'Erbaa', 'Turhal', 'Niksar'] },
  { id: 61, code: '61', name: 'Trabzon', region: 'Karadeniz', districts: ['Ortahisar', 'Akçaabat', 'Araklı', 'Of'] },
  { id: 62, code: '62', name: 'Tunceli', region: 'Doğu Anadolu', districts: ['Merkez', 'Pertek', 'Mazgirt'] },
  { id: 63, code: '63', name: 'Şanlıurfa', region: 'Güneydoğu Anadolu', districts: ['Eyyübiye', 'Haliliye', 'Karaköprü', 'Siverek', 'Viranşehir'] },
  { id: 64, code: '64', name: 'Uşak', region: 'Ege', districts: ['Merkez', 'Banaz', 'Eşme'] },
  { id: 65, code: '65', name: 'Van', region: 'Doğu Anadolu', districts: ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş'] },
  { id: 66, code: '66', name: 'Yozgat', region: 'İç Anadolu', districts: ['Merkez', 'Sorgun', 'Akdağmadeni'] },
  { id: 67, code: '67', name: 'Zonguldak', region: 'Karadeniz', districts: ['Merkez', 'Ereğli', 'Çaycuma'] },
  { id: 68, code: '68', name: 'Aksaray', region: 'İç Anadolu', districts: ['Merkez', 'Ortaköy', 'Eskil'] },
  { id: 69, code: '69', name: 'Bayburt', region: 'Karadeniz', districts: ['Merkez', 'Demirözü', 'Aydıntepe'] },
  { id: 70, code: '70', name: 'Karaman', region: 'İç Anadolu', districts: ['Merkez', 'Ermenek', 'Sarıveliler'] },
  { id: 71, code: '71', name: 'Kırıkkale', region: 'İç Anadolu', districts: ['Merkez', 'Yahşihan', 'Keskin'] },
  { id: 72, code: '72', name: 'Batman', region: 'Güneydoğu Anadolu', districts: ['Merkez', 'Kozluk', 'Sason'] },
  { id: 73, code: '73', name: 'Şırnak', region: 'Güneydoğu Anadolu', districts: ['Merkez', 'Cizre', 'Silopi'] },
  { id: 74, code: '74', name: 'Bartın', region: 'Karadeniz', districts: ['Merkez', 'Amasra', 'Ulus'] },
  { id: 75, code: '75', name: 'Ardahan', region: 'Doğu Anadolu', districts: ['Merkez', 'Göle', 'Çıldır'] },
  { id: 76, code: '76', name: 'Iğdır', region: 'Doğu Anadolu', districts: ['Merkez', 'Tuzluca', 'Aralık'] },
  { id: 77, code: '77', name: 'Yalova', region: 'Marmara', districts: ['Merkez', 'Çiftlikköy', 'Çınarcık'] },
  { id: 78, code: '78', name: 'Karabük', region: 'Karadeniz', districts: ['Merkez', 'Safranbolu', 'Yenice'] },
  { id: 79, code: '79', name: 'Kilis', region: 'Güneydoğu Anadolu', districts: ['Merkez', 'Musabeyli', 'Elbeyli'] },
  { id: 80, code: '80', name: 'Osmaniye', region: 'Akdeniz', districts: ['Merkez', 'Kadirli', 'Düziçi'] },
  { id: 81, code: '81', name: 'Düzce', region: 'Karadeniz', districts: ['Merkez', 'Akçakoca', 'Kaynaşlı'] }
];
