// Canonical PRO-LIG teaching-field catalog.
// Based on the Ministry of National Education / Board of Education teaching-field schedule
// updated by the 19.12.2025 Board decision. Keep this list stable and reuse it
// across public membership applications and coordinator member management.
export const MEB_TEACHING_BRANCHES = [
  "Adalet",
  "Aile ve Tüketici Hizmetleri",
  "Almanca",
  "Arapça",
  "Ayakkabı ve Saraciye Teknolojisi",
  "Beden Eğitimi",
  "Bilişim Teknolojileri",
  "Biyoloji",
  "Biyomedikal Cihaz Teknolojileri",
  "Büro Yönetimi / Büro Yönetimi ve Yönetici Asistanlığı",
  "Coğrafya",
  "Çince",
  "Çocuk Gelişimi ve Eğitimi",
  "Denizcilik",
  "Din Kültürü ve Ahlâk Bilgisi",
  "El Sanatları Teknolojisi",
  "Elektrik-Elektronik Teknolojisi",
  "Endüstriyel Otomasyon Teknolojileri",
  "Felsefe",
  "Fen Bilimleri",
  "Fizik",
  "Fransızca",
  "Gazetecilik",
  "Gemi Yapımı",
  "Gıda Teknolojisi",
  "Giyim Üretim Teknolojisi / Moda Tasarım Teknolojileri",
  "Görsel Sanatlar",
  "Grafik ve Fotoğraf",
  "Güzellik ve Saç Bakım Hizmetleri / Güzellik Hizmetleri",
  "Halkla İlişkiler ve Organizasyon Hizmetleri / Halkla İlişkiler",
  "Harita-Tapu-Kadastro",
  "Hasta ve Yaşlı Hizmetleri",
  "Hayvan Sağlığı / Hayvan Yetiştiriciliği ve Sağlığı",
  "İlköğretim Matematik",
  "İmam-Hatip Lisesi Meslek Dersleri",
  "İngilizce",
  "İnşaat Teknolojisi",
  "İspanyolca",
  "İtalyanca",
  "İtfaiyecilik ve Yangın Güvenliği",
  "Japonca",
  "Kimya / Kimya Teknolojisi",
  "Konaklama ve Seyahat Hizmetleri",
  "Kuyumculuk Teknolojisi",
  "Laboratuvar Hizmetleri",
  "Makine Teknolojisi / Makine ve Tasarım Teknolojisi",
  "Matbaa / Matbaa Teknolojisi",
  "Matematik",
  "Metal Teknolojisi",
  "Metalürji Teknolojisi",
  "Mobilya ve İç Mekân Tasarımı",
  "Motorlu Araçlar Teknolojisi",
  "Muhasebe ve Finansman",
  "Müzik",
  "Müzik Aletleri Yapımı",
  "Okul Öncesi",
  "Özel Eğitim",
  "Pazarlama ve Perakende",
  "Plastik Teknolojisi",
  "Psikoloji",
  "Radyo-Televizyon",
  "Raylı Sistemler Teknolojisi",
  "Rehberlik",
  "Rusça",
  "Sağlık / Sağlık Hizmetleri",
  "Sağlık Bilgisi",
  "Sanat Tarihi",
  "Sanat ve Tasarım / Plastik Sanatlar",
  "Seramik ve Cam Teknolojisi",
  "Sınıf Öğretmenliği",
  "Sosyal Bilgiler",
  "Tarım Teknolojileri / Tarım",
  "Tarih",
  "Teknoloji ve Tasarım",
  "Tekstil Teknolojisi",
  "Tesisat Teknolojisi ve İklimlendirme",
  "Türkçe",
  "Türk Dili ve Edebiyatı",
  "Uçak Bakım",
  "Ulaştırma Hizmetleri",
  "Yenilenebilir Enerji Teknolojileri",
  "Yiyecek İçecek Hizmetleri",
  "Yaşayan Diller ve Lehçeler",
  "Maden Teknolojisi",
  "Farsça",
  "Korece",
  "Geleneksel Türk Sanatları",
  "Tiyatro",
  "Bilim Tarihi",
  "Bilgisayar ve Öğretim Teknolojileri"
] as const;

export type MebTeachingBranch = (typeof MEB_TEACHING_BRANCHES)[number];

export function isMebTeachingBranch(value: string): value is MebTeachingBranch {
  return (MEB_TEACHING_BRANCHES as readonly string[]).includes(value);
}
